// TOKENS
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN'

export const UPDATE_USER_PROPS = 'UPDATE_USER_PROPS'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const REMOVE_USER_AUTH = 'REMOVE_USER_AUTH'
export const REMOVE_CREDENTIALS = 'REMOVE_CREDENTIALS'
export const SET_USER_AUTH = 'SET_USER_AUTH'

// SERVER
export const CHANGE_SERVER_AUTH_STATUS = 'CHANGE_SERVER_AUTH_STATUS'
export const SET_SERVER_AUTH_MESSAGE = 'SET_SERVER_AUTH_MESSAGE'
export const CHANGE_SERVER_REGISTER_STATUS = 'CHANGE_SERVER_REGISTER_STATUS'
export const SET_SERVER_REGISTER_MESSAGE = 'SET_SERVER_REGISTER_MESSAGE'
